### ISSUE TITLE
Big problems with manjaro

### ISSUE THREAD

**Issue by MakaiHanta** [shahnawazshahin/steam-using-gamescope-guide#12]
The first problem is GDM, which is not so easy to change the default environment. All right, I changed it somehow.

Next - flickering image with sound loss when connected to a 4k TV. The flickering worsens when the HDR flag is turned on (I have a 7900 xtx).

Impossibility to use mangohud, because steem reports that some presset is already used. Consequently, nothing can be changed - neither hertzovka, nor anything else.

And lastly - the button to exit to the desktop does not work.

If someone, like me, also uses manjaro, it is better to install a ready-made solution: chimera OS, bazzite or nobara. I'm washing my hands of this and don't want to have to fix it all for months

**Comment by shahnawazshahin** [comment]
Thank you for reaching out. This does work with GDM, so no need to switch to SDDM. The README.md file has been updated that provides instructions to set up and test this for GDM.

Unfortunately I won't be able to recreate the issue with flickering image with sound loss when connect to a 4K TV. However, there are known issues in using 'lib32-amdvlk' with Steam and it is better to use lib32-vulkan-radeon instead. Gamescope also includes flags that could help with optimisation (e.g., '--immediate-flips'. You can find these options by running 'gamescope --help' from the terminal.

As for MangoHud, the recommendation is to use the '--mangoapp' flag when running Steam with Gamescope. Make sure both mangohud and lib32-mangohud packages are installed. You can test this by running 'gamescope --mangoapp -e -- steam -steamdeck -steamos3' from the terminal or command line.

For the option to Switch to Desktop, make sure the /usr/bin/steamos-session-select script is present with execute permissions set (chmod +x /usr/bin/steamos-session-select).

Distributions like Bazzite, ChimeraOS and Nobara takes away the hassle setting up the Steam Deck experience from scratch with a community behind it. But then you're locked in to their distribution of choice (e.g., Fedora) and they have their own set of problems. When setting up from scratch, you have a choice of distribution that supports Gamescope.

I hope this helps. Just wondering, are you running the Flatpack version of Steam? This is something I haven't tried with, and used the package provided by the distribution instead. Also, I haven't used Manjaro in a long while.

**Comment by shahnawazshahin** [comment]
As follow up, I've applied this guide on a mini PC with AMD iGPU running Manjaro with Gnome and GDM and it works fine. I'll update this guide to reflect that it works for other distributions that supports Gamescope.

As you're using Manjaro, there is a package called gamescope-session-steam. Installing this package will achieve similar results and is easier than following this guide as a do-it-yourself approach.

Of course, using distributions like Bazzite will be a lot easier to use is you want to avoid the do-it-yourself approach.

**Comment by MakaiHanta** [comment]
> В качестве продолжения, я применил это руководство на мини-ПК с AMD iGPU под управлением Manjaro с Gnome и GDM, и оно работает нормально. Я обновлю это руководство, чтобы отразить, что оно работает для других дистрибутивов, поддерживающих Gamescope.
> 
> Поскольку вы используете Manjaro, существует пакет под названием gamescope-session-steam. Установка этого пакета позволит достичь аналогичных результатов и будет проще, чем следование этому руководству в качестве самостоятельного подхода.
> 
> Конечно, использование дистрибутивов, таких как Bazzite, будет намного проще в использовании, если вы хотите избежать подхода «сделай сам».

Yeah, I went to download bazzite as soon as I wrote that ticket. And I'm happy with it. Out of the box, full customization of steam and gamescope for TV. Even sleep mode works as well as on the steam deck itself. System updates are downloaded there and installed in silent mode by themselves. And for packages that don't have rpm, flatpak or appimage versions, a GUI program for containerization is already pre-installed. Overall, I'm happy with it

**Comment by shahnawazshahin** [comment]
Sorry for the delay in responding, and I'm glad that you've found a solution. Distributions like Bazzite makes it easier to set up on a Steam Deck or on a living room PC for that console-like experience.

Thank you for taking interest on this project. The intention is to help people understand how Gamescope works with Steam on Linux to provide that SteamOS experience - its pretty much the basis for SteamOS. I hope this has been useful.

I'll mark this ticket as closed in the next few days.
