### ISSUE TITLE
How to switch grom gamescope Session to Kde Plasma (Wayland)

### ISSUE THREAD

**Issue by krolmiki2011** [shahnawazshahin/steam-using-gamescope-guide#14]
Hello, i have a questions how to make switch to desktop grom gamescope steam Session to Kde wayland

**Comment by krolmiki2011** [comment]
PLEASE RESPONSE

**Comment by shahnawazshahin** [comment]
Hi. Sorry for the delay. To make Switch to Desktop to work you need the steamos-session-select script in /usr/bin/. In this script you can call `steam -shutdown`, which will take you back to the login screen (GDM, SDDM). For example:

/usr/bin/steamos-session-select
--
`#!/bin/bash`

`steam -shutdown`

This is described in the README file under [section 8](https://github.com/shahnawazshahin/steam-using-gamescope-guide#8-add-a-script-to-switch-back-to-desktop-mode-back-to-login-screen). I noticed there is a typo in there so I'll make the update to fix this.

It is possible to set KDE Plasma to autologin in to Steam, and when you select Switch to Desktop you will return to the login screen.

If you want to autologin in to Plasma Wayland after selecting Switch to Desktop, you'll need to add instructions in the 'steamos-session-select' script to amend session property in the /etc/sddm.conf.d/kde_settings.conf. But for that to work it requires root access, which gets more complicated.
